version: 1.0.{build}-{branch}
os: Windows Server 2012 R2

shallow_clone: true

init:
  - git config --global core.autocrlf input

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8.x

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get ./...

test_script:
  - ps: go test -v $(go list ./... | sls -n "vendor|_examples")

build:
  verbosity: minimal
deploy: false
